#
#
#
#
#
[RAIN]
linewidth = 1
markersize = 2.0
unit = "mm"   # daily or accumulated rainfall
normal = 30
alert  = 60 
alarm  = 100 

[TILT]
linewidth = 0.5
markersize = 3.0
unit = "mrad"
normal = 1
alert  = 3
alarm  = 5

[ODS]
linewidth = 0.5
markersize = 3.0
unit = "mm"
normal = 5
alert  = 20
alarm  = 100
